# Common configurations

imageCredentials:
  password: ""

domain: ""
license: ""
superusers: ""
mongo:
  url: ""
redis:
  url: ""
stage: "enterprise"
storage: "50Gi"
ssl:
  generator: ""

# Kubernetes Ingress configuration

ingress:
  class: ""
  annotations: {}


# API configurations
api:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Frontend configurations
frontend:
  replicas: 1
  cpu: ""
  memory: ""

  service:
    type: ""


# Proxy configurations
proxy:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Recording configurations
recording:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Sockets configurations
sockets:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""
