apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy-envvars
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
data:
  PORT: "8080"
  STAGE: {{ default "" .Values.stage | quote }}
  DEBUG: {{ default "" .Values.proxy.debug | quote }}
  api_url: {{ printf "http://%s-api-svc:8080" .Release.Name | quote }}
